
package booleanexpressionlab;

/**
 *
 * @author rmw
 */
public class QuestionPanel extends javax.swing.JPanel {
    
    /**
     * You only need to modify code in this method
     */
    
    private void checkExpressions() {
        //For each statement, replace the keyword true with the correct logical expression

        // (a is less than or equal to c) or (a is less than or equal to b)
        result1 = (a <= c) || (a <= b);
        // b is not less than or equal to c
        result2 = !(b <= c);
        // the sum of a and b is greater than c
        result3 = (a+b>c);
        // the product of a and b is less than or equal to 100
        result4 = (a*b<=100);
        // a bitwise OR (b bitwise AND c) is less than 10 where a, b, and c are rounded down
        result5 = ((int) a | ((int) b & (int) c)) < 10;
    }


    /**
     * Creates new form QuestionPane
     */
    public QuestionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valuePanel = new javax.swing.JPanel();
        aLabel = new javax.swing.JLabel();
        aText = new javax.swing.JTextField();
        bLabel = new javax.swing.JLabel();
        bText = new javax.swing.JTextField();
        cLabel = new javax.swing.JLabel();
        cText = new javax.swing.JTextField();
        expression1Label = new javax.swing.JLabel();
        expression2Label = new javax.swing.JLabel();
        expression3Label = new javax.swing.JLabel();
        expression4Label = new javax.swing.JLabel();
        expression5Label = new javax.swing.JLabel();

        valuePanel.setLayout(new java.awt.GridLayout(1, 0));

        aLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        aLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aLabel.setText("a");
        valuePanel.add(aLabel);

        aText.setColumns(7);
        aText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        aText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aText.setText("4.5");
        aText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTextActionPerformed(evt);
            }
        });
        valuePanel.add(aText);

        bLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        bLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bLabel.setText("b");
        valuePanel.add(bLabel);

        bText.setColumns(7);
        bText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        bText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bText.setText("6.0");
        bText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTextActionPerformed(evt);
            }
        });
        valuePanel.add(bText);

        cLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cLabel.setText("c");
        valuePanel.add(cLabel);

        cText.setColumns(7);
        cText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cText.setText("7.5");
        cText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextActionPerformed(evt);
            }
        });
        valuePanel.add(cText);

        expression1Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        expression1Label.setText("(a is less than or equal to c) or (a is less than or equal to b) evaluates to true");

        expression2Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        expression2Label.setText("b is not less than or equal to c evaluates to false");

        expression3Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        expression3Label.setText("the sum of a and b is greater than c evaluates to true");

        expression4Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        expression4Label.setText("the product of a and b is less than or equal to 100 evaluates to true");

        expression5Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        expression5Label.setText("a bitwise OR (b bitwise AND c) is less than 10 where a, b, and c are rounded down evaluates to true");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(valuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expression1Label)
                            .addComponent(expression3Label)
                            .addComponent(expression4Label)
                            .addComponent(expression2Label)
                            .addComponent(expression5Label))))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(valuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(expression1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expression2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expression3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expression4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expression5Label)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTextActionPerformed
        // TODO add your handling code here:
        updateQuestionLabels();
    }//GEN-LAST:event_aTextActionPerformed

    private void bTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTextActionPerformed
        // TODO add your handling code here:
        updateQuestionLabels();
    }//GEN-LAST:event_bTextActionPerformed

    private void cTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextActionPerformed
        // TODO add your handling code here:
        updateQuestionLabels();
    }//GEN-LAST:event_cTextActionPerformed


    private void updateQuestionLabels() {
        a = Double.parseDouble(aText.getText());
        b = Double.parseDouble(bText.getText());
        c = Double.parseDouble(cText.getText());
        checkExpressions();
        expression1Label.setText("(a is less than or equal to c) or (a is less than or equal to b) evaluates to " + result1);
        expression2Label.setText("b is not less than or equal to c evaluates to " + result2);
        expression3Label.setText("the sum of a and b is greater than c evaluates to " + result3);
        expression4Label.setText("the product of a and b is less than or equal to 100 evaluates to " + result4);
        expression5Label.setText("a bitwise OR (b bitwise AND c) is less than 10 where a, b, and c are rounded down evaluates to " + result5);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JTextField aText;
    private javax.swing.JLabel bLabel;
    private javax.swing.JTextField bText;
    private javax.swing.JLabel cLabel;
    private javax.swing.JTextField cText;
    private javax.swing.JLabel expression1Label;
    private javax.swing.JLabel expression2Label;
    private javax.swing.JLabel expression3Label;
    private javax.swing.JLabel expression4Label;
    private javax.swing.JLabel expression5Label;
    private javax.swing.JPanel valuePanel;
    // End of variables declaration//GEN-END:variables

    private boolean result1 = true;
    private boolean result2 = true;
    private boolean result3 = true;
    private boolean result4 = true;
    private boolean result5 = true;
    private double a = 4.5;
    private double b = 6.0;
    private double c = 7.5;
}
