/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ctis210lab14;

import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author keval
 */
public class ImageDisplay extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     */
    public ImageDisplay() {
        initComponents();
        
        ImageIcon firstIcon = new ImageIcon("image1.png");
        image1Label.setIcon(firstIcon);
        
        ImageIcon secondIcon = new ImageIcon("image2.jpg");
        image2Label.setIcon(secondIcon);
        
        image1Label.setHorizontalTextPosition(SwingConstants.CENTER);  
        image1Label.setVerticalTextPosition(SwingConstants.BOTTOM);
        image2Label.setHorizontalTextPosition(SwingConstants.CENTER);  
        image2Label.setVerticalTextPosition(SwingConstants.BOTTOM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image1Label = new javax.swing.JLabel();
        image2Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moving Images");

        image1Label.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        image1Label.setText("Space Image 1");
        image1Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                image1LabelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                image1LabelMouseMoved(evt);
            }
        });
        image1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                image1LabelMouseEntered(evt);
            }
        });
        image1Label.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                image1LabelKeyPressed(evt);
            }
        });

        image2Label.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        image2Label.setText("Space Image 2");
        image2Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                image2LabelMouseDragged(evt);
            }
        });
        image2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                image2LabelMouseEntered(evt);
            }
        });
        image2Label.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                image2LabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(image1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(image2Label)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(image1Label)
                    .addComponent(image2Label))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void image1LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1LabelMouseMoved
        // TODO add your handling code here:
        Point currentLocation = evt.getPoint();
        System.out.println(currentLocation);
        
        Point screenLocation = evt.getLocationOnScreen();  
        Point panelLocation = getLocationOnScreen();  
        System.out.println("Mouse: " + screenLocation + " " + "Panel: " + panelLocation);
    }//GEN-LAST:event_image1LabelMouseMoved

    private void image1LabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1LabelMouseDragged
        // TODO add your handling code here:
        Point screenLocation = evt.getLocationOnScreen();  
        Point panelLocation = getLocationOnScreen();  
        Point newLocation = new Point(screenLocation.x - panelLocation.x,  
        screenLocation.y - panelLocation.y);  
        image1Label.setLocation(newLocation);
    }//GEN-LAST:event_image1LabelMouseDragged

    private void image2LabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image2LabelMouseDragged
        // TODO add your handling code here:
        Point screenLocation = evt.getLocationOnScreen();  
        Point panelLocation = getLocationOnScreen();  
        Point newLocation = new Point(screenLocation.x - panelLocation.x,  
        screenLocation.y - panelLocation.y);  
        image2Label.setLocation(newLocation);
    }//GEN-LAST:event_image2LabelMouseDragged

    private void image1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1LabelMouseEntered
        // TODO add your handling code here:
        image1Label.requestFocus();
    }//GEN-LAST:event_image1LabelMouseEntered

    private void image1LabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_image1LabelKeyPressed
        // TODO add your handling code here:
        
        moveImage(evt);
    }//GEN-LAST:event_image1LabelKeyPressed

    private void image2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image2LabelMouseEntered
        // TODO add your handling code here:
        image2Label.requestFocus();
    }//GEN-LAST:event_image2LabelMouseEntered

    private void image2LabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_image2LabelKeyPressed
        // TODO add your handling code here:
        moveImage(evt);
    }//GEN-LAST:event_image2LabelKeyPressed

    private void moveImage(java.awt.event.KeyEvent evt) {
        javax.swing.JLabel src = (javax.swing.JLabel) evt.getSource();
        Point location = src.getLocation();  
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN -> {
                Point newLocation = new Point(location.x, location.y + 5);
                src.setLocation(newLocation);
            }
            case KeyEvent.VK_LEFT -> {
                Point newLocation = new Point(location.x - 5, location.y);
                src.setLocation(newLocation);
            }
            case KeyEvent.VK_UP -> {
                Point newLocation = new Point(location.x, location.y - 5);
                src.setLocation(newLocation);
            }
            case KeyEvent.VK_RIGHT -> {
                Point newLocation = new Point(location.x + 5, location.y);
                src.setLocation(newLocation);
            }
            case KeyEvent.VK_ESCAPE -> {
                requestFocus();
            }
            default -> {
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image1Label;
    private javax.swing.JLabel image2Label;
    // End of variables declaration//GEN-END:variables
}
