/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctis210lab7;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author keval
 */
public class ApplicantDisplay extends javax.swing.JFrame {

    /**
     * Creates new form ApplicantDisplay
     */
    public ApplicantDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicantPanel = new javax.swing.JPanel();
        introLabel = new javax.swing.JLabel();
        introText = new javax.swing.JTextField();
        advLabel = new javax.swing.JLabel();
        advText = new javax.swing.JTextField();
        operatingLabel = new javax.swing.JLabel();
        operatingText = new javax.swing.JTextField();
        networkingLabel = new javax.swing.JLabel();
        networkingText = new javax.swing.JTextField();
        databaseLabel = new javax.swing.JLabel();
        databaseText = new javax.swing.JTextField();
        algorithmsLabel = new javax.swing.JLabel();
        algorithmsText = new javax.swing.JTextField();
        gpaLabel = new javax.swing.JLabel();
        gpaText = new javax.swing.JTextField();
        applicantLabel = new javax.swing.JLabel();
        applicantText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        applicantPanel.setBackground(new java.awt.Color(0, 0, 0));
        applicantPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        applicantPanel.setPreferredSize(new java.awt.Dimension(360, 187));

        introLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        introLabel.setForeground(new java.awt.Color(0, 255, 255));
        introLabel.setText("Intro To Comp Prog");

        introText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introTextActionPerformed(evt);
            }
        });

        advLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        advLabel.setForeground(new java.awt.Color(0, 255, 255));
        advLabel.setText("Adv Comp Prog");

        advText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advTextActionPerformed(evt);
            }
        });

        operatingLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        operatingLabel.setForeground(new java.awt.Color(0, 255, 255));
        operatingLabel.setText("Operating Systems");

        operatingText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatingTextActionPerformed(evt);
            }
        });

        networkingLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        networkingLabel.setForeground(new java.awt.Color(0, 255, 255));
        networkingLabel.setText("Networking");

        networkingText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkingTextActionPerformed(evt);
            }
        });

        databaseLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        databaseLabel.setForeground(new java.awt.Color(0, 255, 255));
        databaseLabel.setText("Database Systems");

        databaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseTextActionPerformed(evt);
            }
        });

        algorithmsLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        algorithmsLabel.setForeground(new java.awt.Color(0, 255, 255));
        algorithmsLabel.setText("Algorithms");

        algorithmsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algorithmsTextActionPerformed(evt);
            }
        });

        gpaLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        gpaLabel.setForeground(new java.awt.Color(0, 255, 255));
        gpaLabel.setText("Overall GPA");

        gpaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaTextActionPerformed(evt);
            }
        });

        applicantLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        applicantLabel.setForeground(new java.awt.Color(0, 255, 255));
        applicantLabel.setText("Applicant Name");

        applicantText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout applicantPanelLayout = new javax.swing.GroupLayout(applicantPanel);
        applicantPanel.setLayout(applicantPanelLayout);
        applicantPanelLayout.setHorizontalGroup(
            applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(applicantPanelLayout.createSequentialGroup()
                        .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gpaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(algorithmsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(introLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(networkingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(databaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(operatingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(advLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(215, 215, 215)
                        .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operatingText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(networkingText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(databaseText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(introText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(algorithmsText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gpaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(applicantPanelLayout.createSequentialGroup()
                        .addComponent(applicantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applicantText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        applicantPanelLayout.setVerticalGroup(
            applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicantPanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applicantText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(introText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advLabel)
                    .addComponent(advText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operatingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatingText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkingText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(databaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(algorithmsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algorithmsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(applicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(applicantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(applicantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gpaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaTextActionPerformed
        // TODO add your handling code here:
        updateLabel(gpaLabel, gpaText, "Overall GPA");
    }//GEN-LAST:event_gpaTextActionPerformed

    private void algorithmsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algorithmsTextActionPerformed
        // TODO add your handling code here:
        updateLabel(algorithmsLabel, algorithmsText, "Algorithms");
    }//GEN-LAST:event_algorithmsTextActionPerformed

    private void databaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseTextActionPerformed
        // TODO add your handling code here:
        updateLabel(databaseLabel, databaseText, "Database Systems");
    }//GEN-LAST:event_databaseTextActionPerformed

    private void networkingTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkingTextActionPerformed
        // TODO add your handling code here:
        updateLabel(networkingLabel, networkingText, "Networking");
    }//GEN-LAST:event_networkingTextActionPerformed

    private void operatingTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatingTextActionPerformed
        // TODO add your handling code here:
        updateLabel(operatingLabel, operatingText, "Operating Systems");
    }//GEN-LAST:event_operatingTextActionPerformed

    private void advTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advTextActionPerformed
        // TODO add your handling code here:
        updateLabel(advLabel, advText, "Adv Comp Prog");
    }//GEN-LAST:event_advTextActionPerformed

    private void introTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introTextActionPerformed
        // TODO add your handling code here:

        // System.out.println("The string entered is: " + introString);
        // System.out.println("The numerical value is: " + introNumber);

        updateLabel(introLabel, introText, "Intro to Comp Prog");
    }//GEN-LAST:event_introTextActionPerformed

    private void applicantTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantTextActionPerformed
        // TODO add your handling code here:
        setLabelText(applicantLabel, applicantText, "Applicant Name");
        applicantText.setText("");
    }//GEN-LAST:event_applicantTextActionPerformed

    
    
    private void updateLabel(JLabel label, JTextField text, String className) {
        double grade = Double.parseDouble(text.getText());  
        setLabelColor(grade, label);
        setLabelText(grade, label, className);
        text.setText("");
    }
    
    private void setLabelColor(double grade, JLabel label) {
        Color labelColor = calculateColor(grade);
        label.setBackground(labelColor);
        label.setOpaque(true);
    }
    
    private static Color calculateColor(double grade) {
        double redColor = clamp(25 * Math.pow(1.022, grade) + 50 - 25, 0, 255);
        Color returnColor = new Color((int) redColor, 0, 0);
        return returnColor;
    }
    
    private static double clamp(double value, double min, double max) {
        if (value < min) value = min;
        if (value > max) value = max;
        return value;
    }
    
    private void setLabelText(double number, JLabel label, String className) {
        label.setText(className + ": " + number);
    }
    
    private void setLabelText(JLabel label, JTextField text, String before) {
        label.setText(before + ": " + text.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advLabel;
    private javax.swing.JTextField advText;
    private javax.swing.JLabel algorithmsLabel;
    private javax.swing.JTextField algorithmsText;
    private javax.swing.JLabel applicantLabel;
    private javax.swing.JPanel applicantPanel;
    private javax.swing.JTextField applicantText;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JTextField databaseText;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JTextField gpaText;
    private javax.swing.JLabel introLabel;
    private javax.swing.JTextField introText;
    private javax.swing.JLabel networkingLabel;
    private javax.swing.JTextField networkingText;
    private javax.swing.JLabel operatingLabel;
    private javax.swing.JTextField operatingText;
    // End of variables declaration//GEN-END:variables
}
